development:
  adapter: postgresql
  encoding: unicode
  database: distributor_development
  host: localhost
  pool: 5
  username: distributor
  password: 12345678
test: &test
  adapter: postgresql
  encoding: unicode
  database: distributor_test
  host: localhost
  pool: 5
  username: distributor
  password: 12345678
production:
    adapter: postgresql
    encoding: unicode
    host: localhost
    database: distributor_production
    pool: 5
    username: distributor
    password: 12345678
cucumber:
  <<: *test